/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.event.ActionListener;
import java.io.Console;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import dao.TaiKhoanDao;
import entity.CongNhan;
import entity.TaiKhoan;
import javax.swing.event.AncestorListener;
import javax.swing.event.AncestorEvent;


/**
 *
 * @author Van Dat
 */
public class FrmDangNhap extends javax.swing.JFrame {
	public static CongNhan maCNLogin;
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form FrmDangNhap
     */
    public FrmDangNhap() {
        setTitle("PHẦN MỀM CHẤM CÔNG CHO CÔNG NHÂN");
        initComponents();
        setSize(1276, 800);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        lblTenDangNhap = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        txtTenDangNhap.requestFocus();
        txtTenDangNhap.setText("0123748343");
        chkNhoTaiKhoan = new javax.swing.JCheckBox();
        lblQuenMatKhau = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        txtMatKhau = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 650));

        jPanel1.setBackground(new java.awt.Color(37, 109, 133));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PH\u1EA6M M\u1EC0M CH\u1EA4M C\u00D4NG CHO C\u00D4NG NH\u00C2N");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel2)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/login.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(73, 72, 550, 446);

        lblMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        lblMatKhau.setForeground(new java.awt.Color(37, 109, 133));
        lblMatKhau.setText("M\u1EADt kh\u1EA9u");
        jPanel2.add(lblMatKhau);
        lblMatKhau.setBounds(670, 220, 120, 26);

        lblTenDangNhap.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        lblTenDangNhap.setForeground(new java.awt.Color(37, 109, 133));
        lblTenDangNhap.setText("T\u00E0i kho\u1EA3n");
        jPanel2.add(lblTenDangNhap);
        lblTenDangNhap.setBounds(670, 130, 150, 26);

        txtTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDangNhapActionPerformed(evt);
            }
        });
        jPanel2.add(txtTenDangNhap);
        txtTenDangNhap.setBounds(670, 160, 320, 40);

        chkNhoTaiKhoan.setText("Nh\u1EDB t\u00E0i kho\u1EA3n");
        chkNhoTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNhoTaiKhoanActionPerformed(evt);
            }
        });
        jPanel2.add(chkNhoTaiKhoan);
        chkNhoTaiKhoan.setBounds(690, 310, 110, 20);

        lblQuenMatKhau.setText("Qu\u00EAn m\u1EADt kh\u1EA9u");
        jPanel2.add(lblQuenMatKhau);
        lblQuenMatKhau.setBounds(880, 312, 100, 16);

        btnDangNhap.setBackground(new java.awt.Color(6, 40, 61));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(223, 246, 255));
        btnDangNhap.setText("\u0110\u0103ng nh\u1EADp");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnDangNhapActionPerformed(evt);
				} catch (RemoteException | MalformedURLException | NotBoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        jPanel2.add(btnDangNhap);
        btnDangNhap.setBounds(670, 360, 320, 40);
        jPanel2.add(txtMatKhau);
        txtMatKhau.setBounds(670, 252, 320, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void txtTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void chkNhoTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) throws RemoteException, MalformedURLException, NotBoundException, SQLException {
        if(txtTenDangNhap.getText() == "" || txtMatKhau.getPassword().toString() == "")
        {
        	JOptionPane.showMessageDialog(null, "Vui long nhạp SDT va Mat Khau!");
        	return;
        }
        else {
        	TaiKhoanDao taiKhoanDao = (TaiKhoanDao)Naming.lookup("rmi://localhost:1403/taiKhoanDao");
        	TaiKhoan taiKhoan = taiKhoanDao.getTaiKhoan(txtTenDangNhap.getText());
        	
        	if(taiKhoan == null)
        	{
        		JOptionPane.showMessageDialog(null, "Sai tai khoan hoac mat khau1!");
        		return;
        	}
        	else {
        		String pass = new String(txtMatKhau.getPassword());  
				if(taiKhoan.getMatKhau().trim().equals(pass))
				{
					this.setVisible(false);
					maCNLogin = taiKhoan.getMaCN();
					if(maCNLogin.getMaLoai().getMaLoai().equals("ML3"))
					{
						 new FrmXemThongTin().setVisible(true);
					}
					else if (maCNLogin.getMaLoai().getMaLoai().equals("ML2")){
						new FrmLuongCongNhan().setVisible(true);
					}
					else {
						new FrmTrangChu().setVisible(true);						
					}
				}
				else {
					JOptionPane.showMessageDialog(null, "Sai tai khoan hoac mat khau2!");
	        		return;
				}
			}
        	return;
		}
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JCheckBox chkNhoTaiKhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblQuenMatKhau;
    private javax.swing.JLabel lblTenDangNhap;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration                   
}
