/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

import dao.ChamCongDao;
import dao.CongNhanDao;
import entity.CongNhan;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import javax.swing.event.AncestorListener;
import javax.swing.event.AncestorEvent;
import javax.swing.JMenuItem;

/**
 *
 * @author Van Dat
 */
public class FrmLuongCongNhan extends javax.swing.JFrame {
	DefaultTableModel tableModel;
	public static JPanel pnShowCTHD;
	FrmChiTietPhieuLuong frmChiTietPhieuLuong;
    /**
     * Creates new form FrmTrangChu
     * @throws NotBoundException 
     * @throws RemoteException 
     * @throws MalformedURLException 
     * @throws SQLException 
     */
    public FrmLuongCongNhan() throws MalformedURLException, RemoteException, NotBoundException, SQLException {
        setTitle("Quản lý lương công nhân");
        initComponents();
        setSize(1276, 800);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws NotBoundException 
     * @throws RemoteException 
     * @throws MalformedURLException 
     * @throws SQLException 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() throws MalformedURLException, RemoteException, NotBoundException, SQLException {

    	pnShowCTHD = new JPanel();
		pnShowCTHD.setBounds(620, 140, 659, 708);
		getContentPane().add(pnShowCTHD);
		pnShowCTHD.setLayout(new BorderLayout(0, 0));
		pnShowCTHD.setVisible(false);
    	
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtCongDoan = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtSoLuongSPLamDuoc = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtPhuCap = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtDonVi = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtThucNhan = new javax.swing.JTextField();
        txtThucNhan.setForeground(new Color(255, 0, 0));
        Font myFont1 = new Font("Serif", Font.BOLD, 15);
        txtThucNhan.setFont(myFont1);
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        cbNam = new javax.swing.JComboBox<>();
        cbNam.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		try {
					loadLuongCongNhan();
				} catch (MalformedURLException | RemoteException | NotBoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
        	}
        });
        cbThang = new javax.swing.JComboBox<>();
        cbThang.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		try {
					loadLuongCongNhan();
				} catch (MalformedURLException | RemoteException | NotBoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
        	}
        });
        //new FrmChiTietPhieuLuong(null, "PC" + txtMaNhanVien.getText().toLowerCase().toString(), txtHoTen.getText().toString(), txtMaNhanVien.getText().toString()).setVisible(true);
        btnExport = new javax.swing.JButton();
        btnPhieuLuong = new javax.swing.JButton();
        btnPhieuLuong.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		if(txtMaNhanVien.getText().equals("")) {
					JOptionPane.showMessageDialog(null, "Chọn một công nhân để xem phiếu lương!");
				}
				else {
					try {
						pnShowCTHD.setVisible(true);
						frmChiTietPhieuLuong = new FrmChiTietPhieuLuong(new FrmChiTietHDResomseImpl(), txtMaNhanVien.getText().toString(), txtHoTen.getText().toString(),txtCongDoan.getText().toString(), txtSoLuongSPLamDuoc.getText().toString());
						pnShowCTHD.setBounds(400, 140, 400, 450);
						pnShowCTHD.add(frmChiTietPhieuLuong, BorderLayout.CENTER);
					} catch (ClassNotFoundException | SQLException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
					frmChiTietPhieuLuong.setVisible(true);
				}
        	}
        });
        jLabel32 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		FrmQuanLyCongNhan frmQuanLyCongNhan;
				try {
					frmQuanLyCongNhan = new FrmQuanLyCongNhan();
					frmQuanLyCongNhan.setVisible(true);
				} catch (MalformedURLException | RemoteException | NotBoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
        	}
        });
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem5.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
                try {
					new FrmTrangChu().setVisible(true);
				} catch (MalformedURLException | RemoteException | SQLException | NotBoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
        	}
        });
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(37, 109, 133));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 650));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(223, 246, 255));
        jLabel1.setText("LƯƠNG CÔNG NHÂN");

        jPanel1.setBackground(new java.awt.Color(37, 109, 133));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBackground(new java.awt.Color(37, 109, 133));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Mã nhân viên: ");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Họ tên: ");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Công đoạn: ");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("SLSP:");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Phụ cấp: ");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Thuế:");

        txtDonVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					txtDonViActionPerformed(evt);
				} catch (RemoteException | MalformedURLException | NotBoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Thực nhận: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4Layout.setHorizontalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addGap(67)
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addComponent(jLabel24)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(txtHoTen, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addComponent(jLabel23)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(txtMaNhanVien, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)))
        			.addGap(30)
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel26)
        				.addComponent(jLabel25))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(txtCongDoan)
        				.addComponent(txtSoLuongSPLamDuoc, GroupLayout.PREFERRED_SIZE, 172, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addComponent(jLabel27)
        					.addGap(34)
        					.addComponent(txtPhuCap, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addComponent(jLabel28)
        					.addGap(34)
        					.addComponent(txtDonVi, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
        			.addComponent(jLabel29)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(txtThucNhan, GroupLayout.PREFERRED_SIZE, 184, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel23)
        						.addComponent(txtMaNhanVien, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(txtCongDoan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel27)
        						.addComponent(txtPhuCap, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel25))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel24)
        						.addComponent(txtHoTen, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel26)
        						.addComponent(txtSoLuongSPLamDuoc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(txtDonVi, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel28)))
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addGap(26)
        					.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel29)
        						.addComponent(txtThucNhan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4.setLayout(jPanel4Layout);

        JTableHeader tableHeader = jTable2.getTableHeader();
		tableHeader.setFont(new Font("Segoe UI", Font.BOLD, 12));
		tableHeader.setAlignmentY(RIGHT_ALIGNMENT);
		jTable2.setRowHeight(30);
		jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
		((DefaultTableCellRenderer) tableHeader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        jTable2.setModel(tableModel = new DefaultTableModel(
        	new Object[][] {
        		{null, null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null, null},
        	},
        	new String[] {
        		"M\u00E3 NV", "H\u1ECD t\u00EAn", "C\u00F4ng \u0111o\u1EA1n", "SLSP l\u00E0m \u0111\u01B0\u1EE3c", "Ph\u1EE5 c\u1EA5p", "Thu\u1EBF", "T\u1ED5ng l\u01B0\u01A1ng", "Th\u1EF1c nh\u1EADn"
        	}
        ));
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
		centerRenderer.setHorizontalAlignment(JLabel.CENTER);
		DefaultTableCellRenderer centerRenderer2 = new DefaultTableCellRenderer();
		centerRenderer2.setHorizontalAlignment(JLabel.LEFT);
		jTable2.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
		jTable2.getColumnModel().getColumn(1).setCellRenderer(centerRenderer2);
		jTable2.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
		jTable2.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
		jTable2.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
		jTable2.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
		jTable2.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
		jTable2.getColumnModel().getColumn(7).setCellRenderer(centerRenderer);
        jScrollPane2.setViewportView(jTable2);

        jTable2.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				try {
					int rowSelect = jTable2.getSelectedRow();
					String maCN = (String) jTable2.getValueAt(rowSelect, 0);
					String tenCN = (String) jTable2.getValueAt(rowSelect, 1);
					String congDoan = (String) jTable2.getValueAt(rowSelect,2);
					String SLSPLD = jTable2.getValueAt(rowSelect,3).toString();
					String phuCap = (String) jTable2.getValueAt(rowSelect,4);
					String thue = (String) jTable2.getValueAt(rowSelect,5);
					String thucNhan = (String) jTable2.getValueAt(rowSelect,7);
					txtMaNhanVien.setText(maCN);
					txtHoTen.setText(tenCN);
					txtCongDoan.setText(congDoan);
					txtSoLuongSPLamDuoc.setText(SLSPLD);
					txtPhuCap.setText(phuCap);
					txtDonVi.setText(thue);
					txtThucNhan.setText(thucNhan + "VND");
					System.out.println(txtMaNhanVien);
				} catch (Exception e2) {
					// TODO: handle exception
					e2.printStackTrace();
				}
			}
		});
        
        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("BẢNG LƯƠNG CÔNG NHÂN");

        cbNam.setModel(new DefaultComboBoxModel(new String[] {"2019", "2020", "2021", "2022"}));

        cbThang.setModel(new DefaultComboBoxModel(new String[] {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"}));
        
        JLabel lblNewLabel = new JLabel("Tháng: ");
        
        JLabel lblNm = new JLabel("Năm: ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6Layout.setHorizontalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addGap(300)
        			.addComponent(jLabel19)
        			.addGap(144)
        			.addComponent(lblNewLabel)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(cbThang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(lblNm)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(cbNam, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(81, Short.MAX_VALUE))
        		.addGroup(Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 1046, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel19, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        				.addComponent(cbNam, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblNm)
        				.addComponent(cbThang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblNewLabel))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel6.setLayout(jPanel6Layout);

        btnExport.setText("Export Excel");
        btnExport.setToolTipText("");

        btnPhieuLuong.setText("Phiếu lương");
        btnPhieuLuong.setToolTipText("");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("LÆ°u Ã½ : LÆ°Æ¡ng sáº½ Ä‘Æ°á»£c má»Ÿ khi qua ngÃ y 1 má»—i thÃ¡ng, cÃ³ 2 ngÃ y Ä‘á»ƒ chÃ­nh sá»­a sau Ä‘Ã³ há»‡ thá»‘ng sáº½ khÃ³a");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(114)
        					.addComponent(jLabel32)
        					.addPreferredGap(ComponentPlacement.RELATED, 236, Short.MAX_VALUE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(23)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(btnExport, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(btnPhieuLuong, GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
        					.addPreferredGap(ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
        					.addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(28))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(49)
        					.addComponent(btnExport, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(btnPhieuLuong, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, 509, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18)
        			.addComponent(jLabel32, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
        				.addComponent(jLabel1))
        			.addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 644, GroupLayout.PREFERRED_SIZE)
        			.addGap(694))
        );
        jPanel2.setLayout(jPanel2Layout);

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 102));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(200, 30));

        jMenu1.setText("Thông tin");

        jMenuItem1.setText("Cá nhân");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jMenuItem1ActionPerformed(evt);
				} catch (RemoteException | MalformedURLException | NotBoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        jMenuItem2.setText("Lương");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Nhân sự");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Chức năng");

        jMenuItem5.setText("Chấm công");
        jMenu3.add(jMenuItem5);

        jMenuItem4.setText("Đăng xuất");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 1286, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 648, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
        CongNhan maCNLogin = FrmDangNhap.maCNLogin;
        if(maCNLogin.getMaLoai().getMaLoai().equals("ML3"))
		{
        	jMenuItem2.setEnabled(false);
        	jMenuItem3.setEnabled(false);
			jMenuItem5.setEnabled(false);
		}
		else if (maCNLogin.getMaLoai().getMaLoai().equals("ML2")){
			jMenuItem3.setEnabled(false);
			jMenuItem5.setEnabled(false);
		}
		else {
			jMenuItem2.setEnabled(false);		
		}
        
    	loadLuongCongNhan();
    }// </editor-fold>                        

    private void loadLuongCongNhan() throws MalformedURLException, RemoteException, NotBoundException {
		// TODO Auto-generated method stub
    	int tblRow = jTable2.getRowCount();
		for (int i = tblRow - 1; i >= 0; i--) {
			tableModel.removeRow(i);
		}
		CongNhanDao congNhanDao = (CongNhanDao) Naming.lookup("rmi://localhost:1403/congNhanDao");
		ChamCongDao chamCongDao = (ChamCongDao) Naming.lookup("rmi://localhost:1403/chamCongDao");
		int iSumSLSPLamDuoc = 0;
		int iThucNhan = 0;
		int iTongLuong = 0;
		int iDonGia = 0;
		for (CongNhan cn : congNhanDao.getListCongNhan()) {
			iSumSLSPLamDuoc = chamCongDao.getSoLuongSPTrongThang(cbThang.getSelectedItem().toString(), cbNam.getSelectedItem().toString(), cn.getMaCN());
			if(cn.getCongDoan().toString().equals("San Xuat"))
			{
				iDonGia = 20000;
			}
			else if(cn.getCongDoan().toString().equals("Kiem Tra")) {
				iDonGia = 2000;
			}
			else {
				iDonGia = 4000;
			}
			int iPhuCap = (int) (iSumSLSPLamDuoc == 0 ? 0 : 800000);
			iTongLuong = (int) (iSumSLSPLamDuoc * iDonGia + iPhuCap);
			iThucNhan = (int) (iSumSLSPLamDuoc * iDonGia + iPhuCap - (iSumSLSPLamDuoc * iDonGia*0.05));
			tableModel.addRow(new Object[] { cn.getMaCN(), cn.getHoTen(), cn.getCongDoan(), iSumSLSPLamDuoc, iSumSLSPLamDuoc == 0 ? "0" : "800.000", "0.15", String.format("%,8d%n",iTongLuong),String.format("%,8d%n",iThucNhan)});
		}
	}


    private class FrmChiTietHDResomseImpl implements gui.FrmChiTietPhieuLuong.FrmChiTietHDResponse{

		@Override
		public void getResponse(boolean bStatusPnCTHD) {
			// TODO Auto-generated method stub
			if(bStatusPnCTHD == true) {
				pnShowCTHD.setVisible(false);
			}
		}
		
	}
    
	private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
		 new FrmDangNhap().setVisible(true);
    }                                          

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) throws RemoteException, MalformedURLException, NotBoundException {                                           
        FrmXemThongTin frmcnFrmXemThongTin = new FrmXemThongTin();
        frmcnFrmXemThongTin.setVisible(true);
    }                                          

    private void txtDonViActionPerformed(java.awt.event.ActionEvent evt) throws RemoteException, MalformedURLException, NotBoundException {                                         
        // TODO add your handling code here:
        this.setVisible(false);
        new FrmXemThongTin().setVisible(true);
    }                                        

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) throws MalformedURLException, RemoteException, NotBoundException, SQLException {                                           
        // TODO add your handling code here:
        this.setVisible(false);
        new FrmLuongCongNhan().setVisible(true);
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLuongCongNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLuongCongNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLuongCongNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLuongCongNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new FrmLuongCongNhan().setVisible(true);
				} catch (MalformedURLException | RemoteException | NotBoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnPhieuLuong;
    private javax.swing.JComboBox<String> cbNam;
    private javax.swing.JComboBox<String> cbThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtCongDoan;
    private javax.swing.JTextField txtDonVi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtPhuCap;
    private javax.swing.JTextField txtSoLuongSPLamDuoc;
    private javax.swing.JTextField txtThucNhan;
}
